### ISSUE TITLE
Weird spike in DC arson  

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#413] opened 2017-03-08 22:15 UTC
<img width="725" alt="screen shot 2017-03-08 at 12 22 33 pm" src="https://cloud.githubusercontent.com/assets/15899668/23726621/be353202-0409-11e7-99b4-40c4446bf5b0.png">

**Comment by harrisj** [comment] 2017-03-10 20:49
Investigated this, and it seems like there are cases in `arson_month_by_subcat` where `actual_status=3` and the count is positive. If this field works exactly the same as the one in #418, then we should filter those out and that might be the cause of the spike here – one caused by counting records that have been disqualified, not by a crazed arsonist.

**Comment by harrisj** [comment] 2017-03-23 01:48
From the FBI:
> you are correct, those are an artifact from migrating the data from the master file. 
> <FIELD>_Status is a publishable flag that we are using to remove the data from a publication.
> 3 = not useful for publication or trending
> 1 = not useful for trending

**Comment by LarryBafundo** [comment] 2017-03-23 22:19
so @harrisj should we convert this into a bug/issue and prioritize accordingly?

**Comment by harrisj** [comment] 2017-03-23 23:25
Well, I don't know if it's something to prioritize, since we are going to switch to the estimated data for states. I don't know if we'll have estimated data for arsons though? But going to close this, especially since we have #418 already

**Closed by harrisj** 2017-03-23 23:25 UTC
Labels: bug, data quality

**Comment by harrisj** [comment] 2017-05-25 20:49
I just checked and this is still there, but it seems to be in the underlying data. Ah well... 

<img width="766" alt="crime_data_explorer" src="https://cloud.githubusercontent.com/assets/2044/26470010/18e5bcf6-416a-11e7-91b1-56aeb179a182.png">
