### ISSUE TITLE
Define schema to map offense codes

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#221] opened 2016-12-20 16:44 UTC
We need to map the summary & NIBRS offense codes to ensure that we're showing the right data depending on the parameters or characteristics of a search/display, such as crime type and location. 

CJIS has provided us with documentation that explains how this is performed currently, as SRS and NIBRS sometimes refer to the same or similar offenses differently. The CDE will also need to know which data to display depending on the type of data that is being reported by the agencies with a search area.

**Comment by harrisj** [comment] 2016-12-20 18:59
Just to provide a bit of a clarification, it seems to me like we need to determine a few things:

1. Do we need to define a high-level mapping (one code to one or more codes in NIBRS and/or SRS) of our categories to both of the offense code systems in use already or is it sufficient to map NIBRS to SRS and we use NIBRS?
2. We probably need to be a bit more precise about whether we are mapping at the specific offense level and/or the offense categories/classess available in each system. We might just need to map the latter or we might need to support a parallel mapping of our CDE offense category to NIBRS or SRS categories.

**Comment by LarryBafundo** [comment] 2016-12-22 14:02
@harrisj those are good points, but how do we arrive at a decision? does our design direction indicate that we just need to map NIBRS to SRS?

what do you mean by offense levels vs. offense codes? my understanding is that all offenses have a reference code and a description. but am not sure if you're talking about something else.

**Comment by harrisj** [comment] 2016-12-22 15:28
Sorry for being imprecise. Let me actually do my homework here:

The `/incidents/count` endpoint returns nationwide summary records from the RET A Month Offense Subcat table. Each record is a count of a crime for a specific month the `offense_subcat_id` code which looks like `45 - Simple Assault`. These offenses are in turn mapped to a `reta_offense_category` which looks like `40 - Assault` and is like a folder containing the more specific subcategories. The categories are in turn mapped to a broad classification of whether it is a violent crime or a crime against property or such.

NIBRS uses a different hierarchy for offenses. Each NIBRS incident has one or more NIBRS offenses each of which has a specific `nibrs_offense_type` like `26E - Wire Fraud` and which is also listed with a offense category name like `Fraud Offenses` and also a classification if it's a crime against society/property/persons. 

Anyhow, I think I just need to look and see if NIBRS offense codes are a superset of RET A Offense codes (and similarly for NIBRS categories vs. RETA categories). Or if it's the other way around. Or if we need to devise a generic mapping of our own codes to both if one doesn't strictly include the other. I feel like that conversion doc probably has the answers.

**Comment by harrisj** [comment] 2016-12-28 16:09
Maybe I am just overthinking this too. I just am thinking about the URL structure of pages and it seems like we might have something like `/ohio/homicide' or 'ohio/counties/cuyahoga/homicide` or `/ohio/counties/cuyahoga/cleveland-pd/homicide` or something and the issue is that we want `homicide` to return SRS-level data at the county level and NIBRS data at the agency level. But there is no requirement that they have to be that way, and it might be wasting time to do this now. It might be that also while we want to be pretty broad at the state level trends, that we want to provide more granular looks when you get to agencies.  **So, I'm suggesting that we close this issue unless you feel it's important for this mapping to exist. I used to, but I  think I was way wrong.**

If you are curious, here are the details on the scope of the mapping.

|Type|Count|
|-----|------|
|SRS crime categories|9|
|SRS basic crime codes|11| 
|SRS detailed codes|24|
|NIBRS crime categories|24|
|NIBRS detailed codes|64|

The conversion doc makes it pretty clear that converting from NIBRS basic -> SRS basic involves looking at several fields for context, so I think the only way this general mapping would work would be the broad categories. Here are the SRS ones next to the NIBRS ones

|SRS|NIBRS|
|-----|------------------------------------------|
| |Animal Cruelty                           |
| |Arson                                    |
|Assault| Assault Offenses                         |
| |Bribery                                  |
|Burglary| Burglary/Breaking & Entering             |
| |Counterfeiting/Forgery                   |
| |Destruction/Damage/Vandalism of Property |
| |Drug/Narcotic Offenses                   |
| |Embezzlement                             |
| |Extortion/Blackmail                      |
| |Fraud Offenses                           |
| |Gambling Offenses                        |
|Homicide|Homicide Offenses                        |
|Human Trafficking|Human Trafficking                        |
| |Kidnapping/Abduction                     |
|Larceny| Larceny/Theft Offenses                   |
|Motor Vehicle Theft|Motor Vehicle Theft                      |
| |Pornography/Obscene Material             |
| |Prostitution Offenses                    |
|Robbery| Robbery                                  |
|Sex Offenses|Sex Offenses                             |
| |Stolen Property Offenses                 |
| |Weapon Law Violations                    |

There is a lot that would be missed in any mapping. It seems best to just avoid it

**Comment by LarryBafundo** [comment] 2017-01-12 00:10
@harrisj where did we land with this? should we close this out?

**Closed** 2017-01-13 20:44 UTC
