### ISSUE TITLE
Offender ethnicity endpoint is returning "null" for all counts

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#562] opened 2017-06-15 03:41 UTC
The offenders' ethnicity endpoint returns a response where all the `count` values are `null`. This is not the case for the victims' ethnicity endpoint, which is returning values. This seems to be a bug since it is acting the same for all states.

URL: `offenders/count/states/oh/ethnicity/offenses?per_page=250&explorer_offense=homicide`

**Comment by harrisj** [comment] 2017-06-15 14:45
Okay, I just ran:

``` sql
select count(*) from offense_offender_counts where state_id IS NOT NULL AND ethnicity IS NOT NULL
```

And got 42 rows back. Which is _odd_. Will investigate further.

**Comment by harrisj** [comment] 2017-06-15 14:54
Okay, I just did this

``` sql
select count(*) from nibrs_offender where ethnicity_id IS NOT NULL;
```

And got 55 rows back. Which suggests the issue is in the data. Will have to follow up with the FBI.

**Comment by harrisj** [comment] 2017-06-15 16:05
Oops! I was looking at the wrong DB. But when I look at the production DB

1,879 rows with ethnicity in the offense_offender_counts table
618,622 rows with ethnicity_id in the nibrs_offender table. Which is a bit better but only 0.07% of the 87,630,489 offender rows

**Comment by harrisj** [comment] 2017-06-15 16:11
In contrast, 50,897,315 of 84,693,100 nibrs_victim records have an ethnicity (60%)

**Comment by cacraig** [comment] 2017-06-15 16:28
@harrisj  - The offense_offender_counts table is aggregate so those numbers make sense. It seems like ethnicity is just not reported much with offenders.

**Comment by LarryBafundo** [comment] 2017-06-16 20:24
closing. this isn't actually an issue.

**Closed** 2017-06-16 20:24 UTC
Labels: bug
